api/urls.py
from django.conf.urls import url

from api import views

urlpatterns = [
	url(r'^delete', views.queue_delete, name='queue_delete'),
	url(r'^enrich', views.queue_enrich, name='queue_enrich'),
	url(r'^index-web', views.queue_index_web, name='queue_index_web'),
	url(r'^index-rss', views.queue_index_rss, name='queue_index_rss'),
	url(r'^index-file', views.queue_index_file, name='queue_index_file'),
	url(r'^index-filedirectory', views.queue_index_file, name='queue_index_filedirectory'),
	url(r'^index-dir', views.queue_index_file, name='queue_index_dir'),
]

hypothesis/urls.py
from django.conf.urls import url

from hypothesis import views

urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^(?P<pk>\d+)/crawl$', views.crawl, name='crawl'),
	url(r'^recrawl$', views.recrawl, name='recrawl'),
	url(r'^create$', views.create_hypothesis, name='create'),
	url(r'^(?P<pk>\d+)/update$', views.update_hypothesis, name='update'),
]

opensemanticsearch/urls.py
from django.conf.urls import include, url

from django.contrib import admin

from django.contrib import auth


urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'^api/', include('api.urls', namespace="api")),
	url(r'^entity_rest_api/', include('entity_rest_api.urls', namespace="entity_rest_api")),
	url(r'^setup/', include('setup.urls', namespace="setup")),
	url(r'^crawler/', include('crawler.urls', namespace="crawler")),
	url(r'^files/', include('files.urls', namespace="files")),
	url(r'^datasources/', include('datasources.urls', namespace="datasources")),
	url(r'^annotate/', include('annotate.urls', namespace="annotate")),
	url(r'^thesaurus/', include('thesaurus.urls', namespace="thesaurus")),
	url(r'^rss_manager/', include('rss_manager.urls', namespace="rss_manager")),
	url(r'^querytagger/', include('querytagger.urls', namespace="querytagger")),
	url(r'^search-list/', include('search_list.urls', namespace="search_list")),
	url(r'^csv/', include('csv_manager.urls', namespace="csv_manager")),
	url(r'^ontologies/', include('ontologies.urls', namespace="ontologies")),
	url(r'^hypothesis/', include('hypothesis.urls', namespace="hypothesis")),
	url(r'^graph/', include('visual_graph_explorer.urls', namespace="graph")),
	url(r'^search_entity/', include('search_entity.urls', namespace="search_entity")),
	url(r'^morphology/', include('morphology.urls', namespace="morphology")),
	url(r'^twitter/', include('twitter.urls', namespace="twitter")),
]

solr_relevance_ranking_analysis/urls.py
from django.conf.urls import url

from solr_relevance_ranking_analysis import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
]

hypothesis/models.py
from django.db import models


class Hypothesis(models.Model):

	title = models.CharField(max_length=1000, blank=True)
	description = models.TextField(blank=True)

	api = models.CharField(max_length=1000, blank=True)
	token = models.CharField(max_length=1000, blank=True)
	
	last_imported = models.DateTimeField(null=True, blank=True)

	last_update = models.CharField(max_length=1000, blank=True)
	delta = models.IntegerField(default=15)
	
	uri = models.CharField(max_length=1000, blank=True)
	user = models.CharField(max_length=1000, blank=True, default='opensemanticsearch')
	group = models.CharField(max_length=1000, blank=True)
	tag = models.CharField(max_length=1000, blank=True)

	def __str__(self):
		
		title = self.title
		
		if not title:
			title = self.uri

		if not title:
			title = self.user

		if not title:
			title = self.group

		if not title:
			title = self.tag

		if not title:
			title = self.id
	
		return title

hypothesis/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import RequestContext
from django.views import generic
from django.forms import ModelForm
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.utils import timezone

import datetime
from datetime import timedelta

from hypothesis.models import Hypothesis

from opensemanticetl.etl_hypothesis import Connector_Hypothesis 

class HypothesisForm(ModelForm):

	class Meta:
		model = Hypothesis
		fields = '__all__'

class IndexView(generic.ListView):
	model = Hypothesis

class DetailView(generic.DetailView):
	model = Hypothesis

class CreateView(generic.CreateView):
	model = Hypothesis

class UpdateView(generic.UpdateView):
	model = Hypothesis


#
# New/additional import
#

def create_hypothesis(request):

	if request.method == 'POST':

		form = HypothesisForm(request.POST, request.FILES)

		if form.is_valid():
			hypothesis = form.save()

			return HttpResponseRedirect( reverse('hypothesis:detail', args=[hypothesis.pk]) ) # Redirect after POST

	else:
		form = HypothesisForm()

	return render(request, 'hypothesis/hypothesis_form.html', 
			{'form': form,	} )
	

#
# Update
#

def update_hypothesis(request, pk):

	hypothesis = Hypothesis.objects.get(pk=pk)
	
	if request.POST:
		
		form = HypothesisForm(request.POST, request.FILES, instance=hypothesis)
		
		if form.is_valid():
			form.save()

			return HttpResponseRedirect( reverse('hypothesis:detail', args=[pk])) # Redirect after POST
		
			pass
	else:
		form = HypothesisForm(instance=hypothesis)

	return render(request, 'hypothesis/hypothesis_form.html', 
			{'form': form, 'hypothesis': hypothesis } )

#
# ETL - import annotations from Hypothesis
#

def etl_hypothesis(pk):

	hypothesis = Hypothesis.objects.get(pk=pk)

	connector = Connector_Hypothesis()
	
	# authorization
	if hypothesis.api:
	    connector.api = hypothesis.api

	if hypothesis.token:
	    connector.token = hypothesis.token

	# start time
	last_imported = datetime.datetime.now()

	# run import
	last_update = connector.etl_annotations(last_update=hypothesis.last_update, user=hypothesis.user, group=hypothesis.group, tag=hypothesis.tag, uri=hypothesis.uri)

	# new timestamp of last imported annotation
	hypothesis.last_update = last_update

	# set new timestamp of last import / call of search API to start time
	hypothesis.last_imported = last_imported

	hypothesis.save()


def crawl(request, pk):

	etl_hypothesis(pk)

	return render(request, 'hypothesis/hypothesis_crawl.html', {'id': pk,})


#
# Do imports where last import was before configured delta time
#

def recrawl(request):

	verbose = True

	log = []
	count = 0
	count_queued = 0

	for hypothesis in Hypothesis.objects.all():

		count += 1

		if verbose:
			log.append( "Checking delta time for Hypothesis import: {}".format(hypothesis) ) 


		do_import = True

		# If delta time 0 no automatic import
		if not hypothesis.delta:
			do_import = False

		# If delta time, do not import within this time by setting add_to_queue to false
		if hypothesis.delta and hypothesis.last_imported:

			# when next import allowed (because time delta passed)?
			next_import = hypothesis.last_imported + timedelta(minutes=hypothesis.delta)

			# don't check time delta if last import in future (i.e. if system time was wrong)
			if hypothesis.last_imported < timezone.now():

				# if time for next import not reached, do not index
				if timezone.now() < next_import:
					do_import = False

			if verbose:
				log.append( "Last import: {}".format(hypothesis.last_imported) )
				log.append( "Next import: {}".format(next_import) ) 


		if do_import:

			if verbose:
				log.append( "Hypothesis API call: {}".format(hypothesis) ) 
			
			etl_hypothesis(pk=hypothesis.pk)

			count_queued += 1
	
	#
 	# stats / log
 	#
 	
	response = "Hypothesis API calls: {} of {}".format(count_queued, count)

	if len(log) > 0:
		response += "\n\n" + "\n".join(log)
	
	#
	# return response
	#
	
	status = HttpResponse(response)
	status["Content-Type"] = "text/plain" 
	return status

hypothesis/templates/hypothesis/hypothesis_crawl.html
{% extends "datasources_base.html" %}

{% block content %}

<div class="row">
	<div class="small-12 columns">
<p>Hypothesis import done.</p>
	</div>
</div>

<div class="row">
	<div class="small-12 columns">

<a class="button" href="{% url 'hypothesis:detail' id %}">Back to datasource details</a>
	</div>
</div>

{% endblock content %}

hypothesis/templates/hypothesis/hypothesis_detail.html
{% extends "datasources_base.html" %}

{% block content %}

<div class="row">
	<div class="small-12 columns">

<a class="button small" href="{% url 'hypothesis:index' %}">Hypothesis imports (back to list of all)</a>


	</div>
</div>

<div class="row">
	<div class="small-12 columns">

Title or ID:
<h1>{{ hypothesis.title|default:hypothesis.id }}</h1>

	{% if hypothesis.api %}

	API: {{ hypothesis.api }}

	{% endif %}


	{% if hypothesis.token %}

	API Token for authorization: {{ hypothesis.token }}

	{% endif %}


	{% if hypothesis.description %}

	{{ hypothesis.description }}

	{% endif %}

<h2>Filter(s)</h2>

	{% if hypothesis.uri %}
	<p>
	URI: {{ hypothesis.uri }}
	</p>
	{% endif %}

	{% if hypothesis.user %}
	<p>
	User: {{ hypothesis.user }}
	</p>
	{% endif %}

	{% if hypothesis.group %}
	<p>
	Group: {{ hypothesis.group }}
	</p>
	{% endif %}

	{% if hypothesis.tag %}
	<p>
	Tag: {{ hypothesis.tag }}
	</p>
	{% endif %}


	</div>
</div>


<div class="row">
	<div class="small-12 columns">

<h3>Actions</h3>

<a class="button" href="{% url 'hypothesis:crawl' hypothesis.id %}">Import annotations</a></li>

<a class="button" href="{% url 'hypothesis:update' hypothesis.id %}">Edit settings</a>


	</div>
</div>

{% endblock content %}

hypothesis/templates/hypothesis/hypothesis_form.html
{% extends "datasources_base.html" %}

{% block content %}

<form {% if form.is_multipart %}enctype="multipart/form-data"{% endif %} action="" method="post">{% csrf_token %}

    {{ form.non_field_errors }}

<div class="row">

	<div class="small-12 columns">


{% if hypothesis.id %}
<h1>Edit Hypothesis annotations import</h1>
{% else %}
<h1>Add Hypothesis annotations import</h1>
{% endif %}



	</div>
</div>




<div class="row">

	<div class="small-12 columns">


<dl class="tabs" data-tab>
  <dd><a href="#panel-title">Description (optional)</a></dd>
  <dd class="active"><a href="#panel-datasource">Datasource and frequency</a></dd>
  <dd><a href="#panel-filter">User or group (Filters)</a></dd>
</dl>

	</div>
</div>










<div class="tabs-content">

  <section class="content" id="panel-title">


<div class="row">
	<div class="small-12 columns text-center">
<h2>Name or notes</h2>
	</div>
</div>

<div class="row">
	<div class="small-12 columns">


<p>Not necessary, only for managing purpose</p>

        {{ form.title.errors }}
        <label for="id_title">Title:</label>
        {{ form.title }}

<div class="row">

    <div class="small-12 medium-8 columns">
    <h3>Notes</h3>
        {{ form.description.errors }}
        <label for="id_description">Description or Notes</label>
        {{ form.description }}
    </div>


</div>

</section>

  <section class="content active" id="panel-datasource">

<div class="row">

	<div class="small-12 columns text-center">

<h2>API</h2>
<p>URL of Hypothesis API</p>

        {{ form.api.errors }}
        <label for="id_api">API URL:</label>
        {{ form.api }}
<p>Leave empty for default API URL <i>https://hypothes.is/api/</i></p>

<h2>API token for authorization</h2>
<p>Authorization token for Hypothesis</p>

        {{ form.token.errors }}
        <label for="id_token">Token:</label>
        {{ form.token }}
<p>Login to hypothesis, open settings menu "Developer" and click on "Generate your API token"</p>



<h2>Frequency (Delta time)</h2>

        {{ form.delta.errors }}
        <label for="id_delta">Delta time (minutes):</label>
        {{ form.delta }}
	<p><i>For example 60 for importing every hour or 0 for manual import by click on "Import annotations"</i></p>


    </div>


</div>




</section>


<section class="content" id="panel-filter">

<div class="row">

	<div class="small-12 columns text-center">
<p>
Set a filter to import only annotations from an user, from an group, for all documents with a tag or for a single document.
</p>

<p>

<strong>Warning:</strong>
<p>
If you use not an own local Hypothesis instance but the standard hypothes.is webservice, you must set a filter, since instead you will start to import all public annotations of the world.
</p>
But mostly you want to set only one of the filter(s), so you get annotations from an user, from an group or for an document or for a tag.
If you for example setup an username and a tag, you will only get annotations for ONLY this one tag tagged ONLY by this one user.
</p>

<h2>User</h2>
<p>Annotations only from this Hypothesis user account</p>

        {{ form.user.errors }}
        <label for="id_user">User:</label>
        {{ form.user }}
	<p>For example <i>MyHypothesisUsername</i></p>


<h2>Group</h2>
<p>Annotations only from this Hypothesis group</p>

        {{ form.group.errors }}
        <label for="id_group">Group:</label>
        {{ form.group }}
	<p>For example <i>MyHypothesisGroup</i></p>


<h2>Tag</h2>
<p>Annotations for only with this tag</p>

        {{ form.tag.errors }}
        <label for="id_tag">Tag:</label>
        {{ form.tag }}
	<p>For example <i>MyCategory</i></p>


<h2>Document (URL)</h2>
<p>Annotations for only this one document</p>

        {{ form.uri.errors }}
        <label for="id_uri">URI:</label>
        {{ form.uri }}
	<p>For example <i>https://www.opensemanticsearch.org/</i></p>




    </div>


</div>


</section>


<hr>


<div class="row">
    <div class="small-12 columns">

<h2>Save changes</h2>

    <input class="button" type="submit" value="Save" />



{% if hypothesis.id %}
    <a class="button" href="{% url 'hypothesis:detail' hypothesis.id %}">Cancel</a>
{% else %}
    <a class="button" href="{% url 'hypothesis:index' %}">Cancel</a>
{% endif %}

</div>
</div>

</form>
{% endblock content %}

hypothesis/templates/hypothesis/hypothesis_list.html
{% extends "datasources_base.html" %}

{% block content %}


<div class="row">
	<div class="small-12 columns">

<br>
	
<ul class="breadcrumbs"><li><a href="{% url 'datasources:index' %}">Datasources</a></li>

 <li class="current"><a href="#">Hypothesis</a></li> 
  </ul>

<h1>Hypothesis annotations</h1>
<p>Import of Hypothesis annotations by Hypothesis search API</p>

<a class="button" href="{% url 'hypothesis:recrawl' %}">Do imports with passed delta time</a>

<a class="button" href="{% url 'hypothesis:create' %}">Add new import</a>


	</div>
</div>


<div class="row">
	<div class="small-12 columns">
<h2>All Hypothesis imports</h2>



{% if hypothesis_list %}
    <ul>
    {% for hypothesis in hypothesis_list %}
        <li><h2><a href="{% url 'hypothesis:detail' hypothesis.id %}">{{ hypothesis.title|default:hypothesis }}</a></h2>
            <a class="button small" href="{% url 'hypothesis:crawl' hypothesis.id %}">Import now</a>
            <a class="button small" href="{% url 'hypothesis:detail' hypothesis.id %}">Details</a>
            <a class="button small" href="{% url 'hypothesis:update' hypothesis.id %}">Edit settings</a>

        </li>
    
    {% endfor %}
    </ul>
{% else %}
    <p>No Hypothesis imports yet.</p>
{% endif %}


	</div>
</div>


{% endblock content %}

hypothesis/templates/hypothesis/hypothesis_recrawl.html
{% extends "datasources_base.html" %}

{% block content %}

<div class="row">
	<div class="small-12 columns">
<p>Hypothesis imports done.</p>
	</div>
</div>

<div class="row">
	<div class="small-12 columns">

<a class="button" href="{% url 'hypothesis:index' %}">Back</a>
	</div>
</div>

{% endblock content %}