api/urls.py
from django.conf.urls import url

from api import views

urlpatterns = [
	url(r'^delete', views.queue_delete, name='queue_delete'),
	url(r'^enrich', views.queue_enrich, name='queue_enrich'),
	url(r'^index-web', views.queue_index_web, name='queue_index_web'),
	url(r'^index-rss', views.queue_index_rss, name='queue_index_rss'),
	url(r'^index-file', views.queue_index_file, name='queue_index_file'),
	url(r'^index-filedirectory', views.queue_index_file, name='queue_index_filedirectory'),
	url(r'^index-dir', views.queue_index_file, name='queue_index_dir'),
]

csv_manager/urls.py
from django.conf.urls import url

from csv_manager import views

urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^create$', views.CreateView.as_view(), name='create'),
	url(r'^(?P<pk>\d+)/update$', views.UpdateView.as_view(), name='update'),
	url(r'^(?P<pk>\d+)/index_csv$', views.index_csv, name='index_csv'),
	url(r'^(?P<pk>\d+)/preview$', views.preview_csv, name='preview_csv'),
	url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
]

opensemanticsearch/urls.py
from django.conf.urls import include, url

from django.contrib import admin

from django.contrib import auth


urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'^api/', include('api.urls', namespace="api")),
	url(r'^entity_rest_api/', include('entity_rest_api.urls', namespace="entity_rest_api")),
	url(r'^setup/', include('setup.urls', namespace="setup")),
	url(r'^crawler/', include('crawler.urls', namespace="crawler")),
	url(r'^files/', include('files.urls', namespace="files")),
	url(r'^datasources/', include('datasources.urls', namespace="datasources")),
	url(r'^annotate/', include('annotate.urls', namespace="annotate")),
	url(r'^thesaurus/', include('thesaurus.urls', namespace="thesaurus")),
	url(r'^rss_manager/', include('rss_manager.urls', namespace="rss_manager")),
	url(r'^querytagger/', include('querytagger.urls', namespace="querytagger")),
	url(r'^search-list/', include('search_list.urls', namespace="search_list")),
	url(r'^csv/', include('csv_manager.urls', namespace="csv_manager")),
	url(r'^ontologies/', include('ontologies.urls', namespace="ontologies")),
	url(r'^hypothesis/', include('hypothesis.urls', namespace="hypothesis")),
	url(r'^graph/', include('visual_graph_explorer.urls', namespace="graph")),
	url(r'^search_entity/', include('search_entity.urls', namespace="search_entity")),
	url(r'^morphology/', include('morphology.urls', namespace="morphology")),
	url(r'^twitter/', include('twitter.urls', namespace="twitter")),
]

solr_relevance_ranking_analysis/urls.py
from django.conf.urls import url

from solr_relevance_ranking_analysis import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
]

csv_manager/models.py
from django.db import models
from django.core.urlresolvers import reverse

import encodings

class CSV_Manager(models.Model): 

	uri = models.CharField(max_length=1000, blank = True)
	title = models.CharField(max_length=255, blank = True)
	description = models.TextField(blank = True)

	file = models.FileField(upload_to='csv', blank = True)

	# get list of supported encodings for selection
	codecs=[]
	aliases = encodings.aliases.aliases
	for alias in aliases:
		codecs.append(alias)
		codec = aliases[alias]
		codecs.append(codec)

	# dedupe
	codecsunique=[]
	for codec in codecs:
		if not codec in codecsunique:
			codecsunique.append(codec)

	# sort
	codecsunique.sort()
	
	codecschoices=[]
	for codec in codecsunique:
		codecschoices.append( (codec, codec) )


	codec = models.CharField (max_length=255, blank = True, choices=codecschoices,
							help_text = 'Which encoding? (Leave blank for systems default, try modern and international utf-8 or for older german format iso-8859-15)')


	sniff_encoding = models.BooleanField(blank=True, default=True)

	sniff_dialect = models.BooleanField(blank=True, default=False)
	delimiter_is_tab = models.BooleanField(blank = True)
	
	delimiter = models.CharField(max_length=1, blank = True,
								help_text='Leave blank for default , or change to ; or another delimiter char')

	quotechar = models.CharField(max_length=1, blank = True)
	doublequote = models.BooleanField(blank = True)
	escapechar = models.CharField(max_length=1, blank = True)

	title_row = models.IntegerField( blank = True, null = True,
									help_text='Row with column titles. Leave blank if the CSV containes only data and no title row' )
	start_row = models.IntegerField( blank = True, null = True,
									help_text='Row where to start. Leave blank or set to 1 if all rows are data' )

	rows = models.TextField(blank = True)
	rows_include = models.BooleanField(default=False)
	cols = models.TextField(blank = True)
	cols_include = models.BooleanField(default=False)

	def __str__(self):
		return self.uri
	
	def get_absolute_url(self):
		return reverse('csv_manager:detail', kwargs={'pk': self.pk})

csv_manager/forms.py
from django import forms
from django.forms import ModelForm

from encodings.aliases import aliases
from models import CSV_Manager


class CSV_ManagerForm(forms.Form):
#class CSV_ManagerForm(ModelForm):
	title = forms.CharField()
	uri = forms.CharField()
	
	codec = forms.ChoiceField(widget=forms.Select)
    
	separator = forms.CharField()
	quotechar = forms.CharField()
	description = forms.CharField(widget=forms.Textarea)

	file = forms.FileField()

	class Meta:
		model = CSV_Manager
		fields = '__all__'

csv_manager/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse

from csv_manager.models import CSV_Manager
from django.http import HttpResponse 

from django.views import generic

from opensemanticetl.enhance_csv import enhance_csv

import os.path


class IndexView(generic.ListView):
	model = CSV_Manager

class DetailView(generic.DetailView):
	model = CSV_Manager

class CreateView(generic.CreateView):
	model = CSV_Manager
	fields = '__all__'

class UpdateView(generic.UpdateView):
	model = CSV_Manager
	fields = '__all__'


def preview_csv(request, pk):
	table = False

	return render(request, 'csv_manager/csv_manager_preview.html', {'id': pk, 'table': table,})


def index_csv(request, pk):

	# todo:
	# - background thread writing status in db?
	#   after starting thread redirect to reloading (until ready) jobstatus page or ajax part inside status page
	# - collect exceptions for error log / status message

	verbose = True
	
	csvmanager = CSV_Manager.objects.get(pk=pk)
	
	#
	# Read parameters from form and set parameters for the csv data enrichment
	#

	if csvmanager.file:
		csvfilename = csvmanager.file.path
		id = csvmanager.file.name
		
	else:
		csvfilename = csvmanager.uri
		id = csvmanager.uri
	
	
	if csvmanager.delimiter_is_tab:
		delimiter = "\t"
	else:
		delimiter = csvmanager.delimiter

		
	data = {}
		
	parameters={}

	parameters['id']= id

	parameters['verbose'] = verbose

	parameters['filename'] = csvfilename

	parameters['delimiter'] = delimiter
	
	if csvmanager.codec:
		parameters['encoding'] = csvmanager.codec
	if csvmanager.quotechar:
		parameters['quotechar'] = csvmanager.quotechar

	parameters['doublequote'] = csvmanager.doublequote
	
	parameters['escapechar'] = csvmanager.escapechar
	
	parameters['sniff_dialect'] = csvmanager.sniff_dialect
	
	parameters['sniff_encoding'] = csvmanager.sniff_encoding
	
	parameters['title_row'] = csvmanager.title_row
	
	parameters['start_row'] = csvmanager.start_row

	parameters['cols'] = csvmanager.cols
	parameters['rows'] = csvmanager.rows
	parameters['cols_include'] = csvmanager.cols_include
	parameters['rows_include'] = csvmanager.rows_include




	# extract a list of row numbers as integer from new line and comma seperated list (textfield)
	rows = []

	for row in csvmanager.rows:
		
		for number in row.split(","):
			try:
				rows.append( int(number) )
			except:
				print ("Error converting string value to included line number: {}".format(number))
	
	parameters['rows'] = rows

	parameters['rows_include'] = csvmanager.rows_include


	# extract a list of column numbers as integer from new line and comma seperated list (textfield)
	cols = []

	for col in csvmanager.cols:
		
		for number in col.split(","):
			try:
				cols.append( int(number) )
			except:
				print ("Error converting string value to included line number: {}".format(number))
	
	parameters['cols'] = cols

	parameters['cols_include'] = csvmanager.cols_include



	#
	# Start data enrichment plugin
	#
	
	etl = enhance_csv()

	count = etl.enhance_csv ( parameters=parameters, data=data )


	return render(request, 'csv_manager/csv_manager_import.html', {'id': pk, 'count': count,})

csv_manager/templates/csv_manager/csv_manager_detail.html
{% extends "datasources_base.html" %}

{% block content %}

<div class="row">
	<div class="small-12 columns">

<a class="button small" href="{% url 'csv_manager:index' %}">Home (back to list of all tables)</a>


	</div>
</div>

<div class="row">
	<div class="small-12 columns">

Title or ID:
<h1>{{ csv_manager.title|default:csv_manager.id }}</h1>

	{% if csv_manager.description %}

	{{ csv_manager.description }}

	{% endif %}

	</div>
</div>


<div class="row">
	<div class="small-12 columns">

<p>
URI or filename:
<h2>{{ csv_manager.uri|default:csv_manager.file.name }}</h2>
</p>

	</div>
</div>

<div class="row">
	<div class="small-12 columns">

<h3>Format</h3>

	</div>
</div>

<div class="row">
	<div class="small-12 medium-6 columns">


<h4>Charset</h4>

<p>Encoding autodetection:

{% if csv_manager.sniff_encoding %}
on
</p>

{% else %}
off
</p>

<p>Setting: {{ csv_manager.codec|default:"Default (UTF-8)" }}</p>

{% endif %}




	</div>

	<div class="small-12 medium-6 columns">


<h4>CSV dialect</h4>



<p>Automatic CSV dialect detection:

{% if csv_manager.sniff_dialect %}
on
{% else %}
off
{% endif %}
</p>



{% if csv_manager.delimiter_is_tab %}

<p>Delimiter: Tabulator (TSV)</p>

{% elif csv_manager.delimiter %}

<p>Delimiter: {{ csv_manager.delimiter|default:"," }}</p>

{% endif %}


{% if csv_manager.quotechar %}

<p>Quote char: {{ csv_manager.quotechar|default:"\"" }}</p>

{% endif %}

{% if csv_manager.escapechar %}

<p>Escape char: {{ csv_manager.escapechar }}</p>

{% endif %}


<p>Double quote:

{% if csv_manager.doublequote %}
on
{% else %}
off
{% endif %}
</p>


	</div>
</div>

<div class="row">
	<div class="small-12 columns">

<h3>Actions</h3>

<a class="button" href="{% url 'csv_manager:update' csv_manager.id %}">Edit settings</a>

<a class="button" href="{% url 'csv_manager:preview_csv' csv_manager.id %}">Preview table with this settings</a></li>

<a class="button" href="{% url 'csv_manager:index_csv' csv_manager.id %}">Import table with this settings to search engine</a></li>



	</div>
</div>

{% endblock content %}

csv_manager/templates/csv_manager/csv_manager_form.html
{% extends "datasources_base.html" %}

{% block content %}

<form {% if form.is_multipart %}enctype="multipart/form-data"{% endif %} action="" method="post">{% csrf_token %}

    {{ form.non_field_errors }}

<div class="row">

	<div class="small-12 columns">

<h1>Edit meta and format data of the CSV table</h1>


	</div>
</div>




<div class="row">

	<div class="small-12 columns">


<dl class="tabs" data-tab>
  <dd><a href="#panel-title">Description</a></dd>
  <dd class="active" title="URI or Upload"><a href="#panel-datasource">Datasource</a></dd>
  <dd><a href="#panel-format">Format (charset &amp; dialect)</a></dd>
  <dd><a href="#panel-mapping">Column names (field mapping)</a></dd>
  <dd title="Exclude parts like content lines (content parts) or columns (datafields)"><a href="#panel-exclude">Exclude</a></dd>
</dl>

	</div>
</div>









<div class="tabs-content">

  <section class="content" id="panel-title">


<div class="row">
	<div class="small-12 columns text-center">
<h2>Name or notes</h2>
	</div>
</div>

<div class="row">
	<div class="small-12 columns">


<p>Not necessary, only for managing purpose</p>

        {{ form.subject.errors }}
        <label for="id_subject">Title:</label>
        {{ form.title }}

<div class="row">

    <div class="small-12 columns">
    <h3>Notes</h3>
        {{ form.description.errors }}
        <label for="id_description">Description or Notes</label>
        {{ form.description }}
    </div>

</div>

</section>

  <section class="content active" id="panel-datasource">

<div class="row">

	<div class="small-12 columns text-center">

<h2>Datasource (CSV file)</h2>
<p>Set an URI (Reference) or upload a csv file</p>
	</div>

</div>

<div class="row">

    <div class="small-12 medium-5 columns">
	<h3>Reference</h3>
	<p>Reference to existing file or external web resource:</p>
        {{ form.uri.errors }}
        <label for="id_uri">URI:</label>
        {{ form.uri }}
	For example <i>file:///dirname/filename.csv</i> for local files or <i>http://www.data.domain/data.csv</i> for a web resource

    </div>

    <div class="small-12 medium-2 columns text-center">
	OR
	</div>
    <div class="small-12 medium-5 columns">
<h3>Upload</h3>
<p>Upload a csv file</p>
        {{ form.file.errors }}
        <label for="id_file">File:</label>
        {{ form.file }}
    </div>


</div>

</section>
  <section class="content" id="panel-format">

<div class="row">

    <div class="small-12 columns text-center">

<h2>Format</h2>

<p>Leave empty for default settings (Excel dialect)<br />
Or enable autodetection (which often will not detect the right options)<br />
And / or set and overwrite (some) options manually</p>

</div>

    <div class="small-12 medium-6 columns">
<h3>Charset</h3>

        {{ form.sniff_encoding.errors }}
        {{ form.sniff_encoding }}
        <label for="id_sniff_encoding">Encoding autodetection (analyze data and guess format)</label>

		<p>Or set other charset manually:</p>

        {{ form.codec.errors }}
        <label for="id_codec">Charset:</label>
        {{ form.codec }}
    <p>Leave empty and disable autodetection for modern, universal and international default (UTF-8) or if needet (because autodetection or this default UTF-8 results to corrupted data espacially on special chars) try with older charsets:</p>
    <p>For example iso8859-15 for former western european or german standard or cp1252 for western european standard encoded with windows)</p>
    </div>


    <div class="small-12 medium-6 columns">
<h3>CSV dialect</h3>

        {{ form.sniff_dialect.errors }}
        {{ form.sniff_dialect }}
        <label for="id_sniff_dialect">Automatic detection of CSV dialect (analyze data and guess format)</label>
<p>Most CSV are standard format and the sniffer often does not autodetect quoted content with multiple lines, so try without autodetection first.</p>

<p>All following settings will overwrite standard settings or automatically detected or guessed values:</p>

<h4>Delimiter</h4>
        {{ form.delimiter.errors }}
        <label for="id_delimiter">Delimiter char:</label>
        {{ form.delimiter }}
<p>Leave empty for default , (comma) or set to ; (semikolon) or another char used as delimiter</p>


        {{ form.delimiter_is_tab.errors }}
        {{ form.delimiter_is_tab }}
        <label for="id_delimiter_is_tab">Use tabulator as delimiter</label>
<p>If this CSV (comma seperated values) is a TSV (tab seperated values)</p>

<h4>Quotechar</h4>
        {{ form.quotechar.errors }}
        <label for="id_quotechar">Quote char:</label>
        {{ form.quotechar }}
<p>Leave empty for default " or set to another char used as quotechar (i.e. if a field contains a text with more than one line the next line shound not be considered as new row if in quote chars)</p>

        {{ form.escapechar.errors }}
        <label for="id_escapechar">Escape char:</label>
        {{ form.escapechar }}
<p>Leave empty for none or set to another char like \ used as escapeechar)</p>

        {{ form.doublequote.errors }}
        {{ form.doublequote }}
        <label for="id_doublequote">Use doublequote instead of escape char</label>
<p>Quote chars inside quotes are masked by doubling the quote char</p>



    </div>


</div>

</section>


<section class="content" id="panel-mapping">

<div class="row">


    <div class="small-12 columns text-center">

<h2>Column titles and field mapping</h2>
<p>If you dont want the columns named "Column 1", "Column 2" ... map custom titles:</p>
</div>
    <div class="small-12 medium-6 columns">
    <h3>Extract titles from row in CSV</h3>
        {{ form.title_row.errors }}
        <label for="id_description">Title row:</label>
        {{ form.title_row }}
        <p>Leave 0 if no title row. Or set to the line number where to find titles (1 if titles are in the first line, 2 if titles stored in the second line...)</p>
    </div>



    <div class="small-12 medium-6 columns">

<h3>Header offset</h3>

        {{ form.start_row.errors }}
        <label for="id_description">First data row:</label>
        {{ form.start_row }}
        <p>First line of data. Leave empty or set to 1 if no titles (only data and beginning at first line), or set to 2 for data beginning at the second line (if first line titles) or to a higher value, if there is a longer header</p>
    </div>

</div>


</section>




<section class="content" id="panel-exclude">

<div class="row">


    <div class="small-12 columns text-center">

<h2>Include or exclude parts</h2>

<p>Settings to import only parts of the CSV spreadsheet.</p>

<p>Leave empty to import all columns of all lines (default).</p>
</div>

    <div class="small-12 medium-6 columns">
    <h3>Rows (Lines or data sets)</h3>


        {{ form.rows_include.errors }}
        {{ form.rows_include }}
        <label for="id_rows_include">Include only defined rows or lines instead of exclude them</label>

        {{ form.rows.errors }}
        <label for="id_rows">Lines / rows:</label>
        {{ form.rows }}
        <p>List (delimited by comma or new lines) of row / line numbers (content parts)</p>
    </div>



    <div class="small-12 medium-6 columns">
    <h3>Columns / Fields (single data fields of each dataset, line or row)</h3>

        {{ form.cols_include.errors }}
        {{ form.cols_include }}
        <label for="id_cols_include">Include only defined columns instead of exclude them</label>


        {{ form.cols.errors }}
        <label for="id_cols">Columns:</label>
        {{ form.cols }}
        <p>List (delimited by comma or new lines) of column numbers (concerning all lines)</p>
    </div>

</section>




</div>

<hr>


<div class="row">
    <div class="small-12 columns">

<h2>Save changes</h2>

    <input class="button" type="submit" value="Save" />



{% if csvmanager.id %}
    <a class="button" href="{% url 'csv_manager:detail' csvmanager.id %}">Cancel</a>
{% else %}
    <a class="button" href="{% url 'csv_manager:index' %}">Cancel</a>
{% endif %}

</div>
</div>

</form>
{% endblock content %}

csv_manager/templates/csv_manager/csv_manager_import.html
{% extends "datasources_base.html" %}

{% block content %}

<div class="row">
	<div class="small-12 columns">
<p>Imported CSV with {{ count }} rows ...</p>
	</div>
</div>

<div class="row">
	<div class="small-12 columns">

<a class="button" href="{% url 'csv_manager:detail' id %}">Back to dataset details</a>
	</div>
</div>

{% endblock content %}

csv_manager/templates/csv_manager/csv_manager_list.html
{% extends "datasources_base.html" %}

{% block content %}

<div class="row">
	<div class="small-12 columns">
<h1>Add new</h1>
<a class="button" href="{% url 'csv_manager:create' %}">Add new CSV table</a>
	</div>
</div>


<div class="row">
	<div class="small-12 columns">
<h1>Existing CSV tables</h1>

{% if csv_manager_list %}
    <ul>
    {% for csv_manager in csv_manager_list %}
        <li><h2><a href="{% url 'csv_manager:detail' csv_manager.id %}">{{ csv_manager.title|default:csv_manager.id }}</a></h2>
            <a class="button small" href="{% url 'csv_manager:detail' csv_manager.id %}">Details</a>
            <a class="button small" href="{% url 'csv_manager:update' csv_manager.id %}">Edit settings</a>
            <a class="button small" href="{% url 'csv_manager:preview_csv' csv_manager.id %}">Preview data formated with this CSV settings</a>
			<a class="button small" href="{% url 'csv_manager:index_csv' csv_manager.id %}">Import to Solr now</a></li>

        </li>
    
    {% endfor %}
    </ul>
{% else %}
    <p>No CSV are available.</p>
{% endif %}


	</div>
</div>


{% endblock content %}

csv_manager/templates/csv_manager/csv_manager_preview.html
{% extends "datasources_base.html" %}

{% block content %}

<p>Preview not implemented yet.</p>

<table>

</table>

{% endblock content %}