api/urls.py
from django.conf.urls import url

from api import views

urlpatterns = [
	url(r'^delete', views.queue_delete, name='queue_delete'),
	url(r'^enrich', views.queue_enrich, name='queue_enrich'),
	url(r'^index-web', views.queue_index_web, name='queue_index_web'),
	url(r'^index-rss', views.queue_index_rss, name='queue_index_rss'),
	url(r'^index-file', views.queue_index_file, name='queue_index_file'),
	url(r'^index-filedirectory', views.queue_index_file, name='queue_index_filedirectory'),
	url(r'^index-dir', views.queue_index_file, name='queue_index_dir'),
]

opensemanticsearch/urls.py
from django.conf.urls import include, url

from django.contrib import admin

from django.contrib import auth


urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'^api/', include('api.urls', namespace="api")),
	url(r'^entity_rest_api/', include('entity_rest_api.urls', namespace="entity_rest_api")),
	url(r'^setup/', include('setup.urls', namespace="setup")),
	url(r'^crawler/', include('crawler.urls', namespace="crawler")),
	url(r'^files/', include('files.urls', namespace="files")),
	url(r'^datasources/', include('datasources.urls', namespace="datasources")),
	url(r'^annotate/', include('annotate.urls', namespace="annotate")),
	url(r'^thesaurus/', include('thesaurus.urls', namespace="thesaurus")),
	url(r'^rss_manager/', include('rss_manager.urls', namespace="rss_manager")),
	url(r'^querytagger/', include('querytagger.urls', namespace="querytagger")),
	url(r'^search-list/', include('search_list.urls', namespace="search_list")),
	url(r'^csv/', include('csv_manager.urls', namespace="csv_manager")),
	url(r'^ontologies/', include('ontologies.urls', namespace="ontologies")),
	url(r'^hypothesis/', include('hypothesis.urls', namespace="hypothesis")),
	url(r'^graph/', include('visual_graph_explorer.urls', namespace="graph")),
	url(r'^search_entity/', include('search_entity.urls', namespace="search_entity")),
	url(r'^morphology/', include('morphology.urls', namespace="morphology")),
	url(r'^twitter/', include('twitter.urls', namespace="twitter")),
]

search_list/urls.py
from django.conf.urls import url

from search_list import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
]

solr_relevance_ranking_analysis/urls.py
from django.conf.urls import url

from solr_relevance_ranking_analysis import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
]

search_list/models.py
from django.db import models

search_list/views.py
from django.shortcuts import render

from django.contrib.auth.decorators import login_required

from django.http import HttpResponse 
from django.shortcuts import render

from django import forms

import urllib
import json
import os

import opensemanticetl.export_solr
from opensemanticetl.export_solr import export_solr

class ListForm(forms.Form):
	list = forms.CharField(widget=forms.Textarea)
	
	filterquery = forms.CharField(widget=forms.TextInput, required=False)

	stopwords = forms.CharField(widget=forms.Textarea, required=False)
	
	raw = forms.BooleanField(required=False, initial=False)
	
	do_find_phrase = forms.BooleanField(required=False, initial=True)
	do_find_near = forms.BooleanField(required=False, initial=True)
	do_find_and = forms.BooleanField(required=False, initial=True)
	do_find_or = forms.BooleanField(required=False, initial=True)
	do_find_similar_and = forms.BooleanField(required=False, initial=True)
	do_find_similar_or = forms.BooleanField(required=False, initial=True)


def index(request):

	verbose = False

	uri_search="/search/?q="


	if request.method == 'POST': # If the form has been submitted...
		form = ListForm(request.POST) # A form bound to the POST data
		if form.is_valid():

			list = form.cleaned_data['list']
			list = list.split("\n")

			stopwords = form.cleaned_data['stopwords']
			filterquery = form.cleaned_data['filterquery']
			stopwords = stopwords.split("\n")
			

			do_find_phrase = form.cleaned_data['do_find_phrase']
			do_find_near = form.cleaned_data['do_find_near']
			do_find_and = form.cleaned_data['do_find_and']
			do_find_or = form.cleaned_data['do_find_or']
			do_find_similar_and = form.cleaned_data['do_find_similar_and']
			do_find_similar_or = form.cleaned_data['do_find_similar_or']

	
			
			# search all the lines
			(found, found_near, found_and, found_or, found_similar_and, found_similar_or, rowcount, error_messages) = search_list(list, verbose=verbose, filterquery=filterquery, stopwords=stopwords, do_find_phrase=do_find_phrase, do_find_near=do_find_near,do_find_and=do_find_and,do_find_or=do_find_or,do_find_similar_and=do_find_similar_and, do_find_similar_or=do_find_similar_or)

			return render(request, 'index.html', 
				{	
					"form": form,
					"uri_search": uri_search,
					"error_messages": error_messages,

					"results": found,
					"found": len(found),

					"results_near": found_near,
					"found_near": len(found_near),

					"results_and": found_and,
					"found_and": len(found_and),
					
					"results_similar_and": found_similar_and,
					"found_similar_and": len(found_similar_and),

					"results_or": found_or,
					"found_or": len(found_or),
					
					"results_similar_or": found_similar_or,
					"found_similar_or": len(found_similar_or),

					"rowcount": rowcount
				})

		else:
			return render(request, 'index.html', {'form': form,})

	else:
		form = ListForm() # An unbound form

		return render(request, 'index.html', {'form': form,}) #!/usr/bin/python


def clean_and_mask(query, operator = None, similar=False, stopwords=None):

	#todo: change NOT to not because if in name it should not be interpreted as search operator


	# clean and lowercase stopwords
	if stopwords:
		cleanedstopwords=[]
		for stopword in stopwords:
			
			stopword = stopword.strip()
			
			stopword = stopword.strip("\"")
			
			stopword = stopword.lower()
			
			cleanedstopwords.append(stopword)

		stopwords = cleanedstopwords

	else:
		stopwords = []
				

	query = query.strip()
	query = query.strip("\"")

	# strip beginning "-" (which sometimes is in names but would be interpreted as search operator that docs with this word would be excluded
	words = query.split()
	query = []
	for word in words:
		while word.startswith('-'):
			word = word.replace("-", '', 1)

		if not word.lower() in stopwords:

			word = opensemanticetl.export_solr.solr_mask(word)

			if similar:
				word = word + '~'

			query.append(word)
	
	if operator:
		delimiter = ' ' + operator + ' '
		query = delimiter.join(query)
	else:
		query = ' '.join(query)


	return query



def search(query, filterquery=None, operator='AND'):

	count = 0

	solr_host = 'http://localhost:8983/solr/'
	if os.getenv('OPEN_SEMANTIC_ETL_SOLR'):
		solr_host = os.getenv('OPEN_SEMANTIC_ETL_SOLR')

	uri = solr_host + 'opensemanticsearch/select?q.op=' + operator + '&wt=json&deftype=edismax&fl=id,score&hl=true&hl.fl=*'
	uri += '&q=' + urllib.parse.quote( query )

	if filterquery:
		uri += '&fq=' + urllib.parse.quote( filterquery )
		
	link = query
	
	request = urllib.request.urlopen( uri )
	encoding = request.info().get_content_charset('utf-8')
	data = request.read().decode(encoding)
	request.close()
	
	result = json.loads(data)

	count = result['response']['numFound']
	
	# preview data
	previews = None
	maxscore = 0
	if count:

		maxscore = str(result['response']['maxScore'])
	
		previews = []
		for doc in result['response']['docs']:
			score = doc['score']
			previews.append( {score:score} )
	
	return link, count, maxscore, previews



def search_list(list, verbose=False, filterquery=None, stopwords=None, do_find_phrase=True, do_find_near=True, do_find_and=True, do_find_or=True, do_find_similar_and=True, do_find_similar_or=True ):
	
	#todo queries_done als sammlung zum ausschliessen mit for query_done in queries_done...
	
	error_messages=[]
	rowcount = 0
	found = {}
	found_near = {}

	found_and = {}
	found_or = {}
	found_similar_and = {}
	found_similar_or = {}


	for line in list:
		
		# strip emtpy
		line = line.strip()

		if not line=='':
			
			rowcount = rowcount + 1

			try:
		
				#
				# exact matches with phrase search with "
				#
	
				query_phrase = "\"" + clean_and_mask(line) + "\""

				count = False
				if do_find_phrase:
					link, count, maxscore, previews = search(query_phrase, filterquery=filterquery)
	
				if count:
					found[line] = { 'count': count, 'link':link }
					if verbose:
						print ("Found " + str(count) +" for full phrase " + line)



				#
				# exact this words in this direction but allow words in between
				#
				max_words_between = 10
				query_near = "\"" + clean_and_mask(line, stopwords=stopwords) + "\"" + '~' + str(max_words_between)

				query = query_near
				
				# if yet searched, exclude former results
				if do_find_phrase:
					query = query + " AND NOT " + query_phrase

				count = False
				if do_find_near:
					link, count, maxscore, previews = search(query, filterquery=filterquery)
	
				if count:
					found_near[line] = { 'count': count, 'link':link, 'maxscore': maxscore, 'previews': previews }
					if verbose:
						print ("Found " + str(count) +" for full phrase with some words in between " + line)



				#
				# all words (and)
				#
				query_and = clean_and_mask(line, 'AND', stopwords=stopwords)
				
				query = query_and
				# if yet searched, exclude former results
				if do_find_phrase:
					query = query + " AND NOT " + query_phrase

				count = False
				if do_find_and:
					link, count, maxscore, previews = search(query, filterquery=filterquery)
	
				if count:
					found_and[line] = {'count': count, 'link':link, 'maxscore': maxscore, 'previews': previews }

					if verbose:
						print ("Maybe found (all words of phrase in document or row) " + str(count) + " for " + line)
		
		
		
				#
				# some words (or)
				#
				query_or = clean_and_mask(line, 'OR', stopwords=stopwords)

				query = "(" + query_or + ")"

				# if yet searched, exclude former results
				if do_find_and:
					query = query + " AND NOT (" + query_and + ")"

				if not do_find_and and do_find_phrase:
					query = query + " AND NOT (" + query_phrase + ")"
				
				count = False
				if do_find_or:

					link, count, maxscore, previews = search(query, filterquery=filterquery)
	
				if count:
					found_or[line] = {'count': count, 'link':link, 'maxscore': maxscore, 'previews': previews }
					if verbose:
						print ("Maybe found (some words of phrase in document or row) " + str(count) + " for " + line)
		

		
				#
				# similar words all (and)
				#
				query_similar_and = clean_and_mask(line, operator='AND', similar=True, stopwords=stopwords)

				query = "(" + query_similar_and + ")"

				# if yet searched, exclude former results
				if do_find_and:
					query = query + " AND NOT (" + query_and + ")"

				if not do_find_and and do_find_phrase:
					query = query + " AND NOT (" + query_phrase + ")"


				count = False
				if do_find_similar_and:
					link, count, maxscore, previews = search(query, filterquery=filterquery)
	
				if count:
					found_similar_and[line] = {'count': count, 'link':link, 'maxscore': maxscore, 'previews': previews }
					if verbose:
						print ("Maybe found (all words of phrase in document or row) " + str(count) + " for " + line)
		

		
				#
				# similar words some (or)
				#
				query_similar_or = clean_and_mask(line, operator='OR', similar=True, stopwords=stopwords)


				query = "(" + query_similar_or + ")"

				# if yet searched, exclude former results
				
				if do_find_and:
					query = query + " AND NOT (" + query_and + ")"
				if not do_find_and and do_find_phrase:
					query = query + " AND NOT (" + query_phrase + ")"
				
				if do_find_similar_and:
					query = query + " AND NOT (" + query_similar_and + ")"
	
				count = False
				if do_find_similar_or:
					link, count, maxscore, previews = search(query, filterquery=filterquery)

				if count:
					found_similar_or[line] = {'count': count, 'link':link, 'maxscore': maxscore, 'previews': previews }
					if verbose:
						print ("Maybe found (all words of phrase in document or row) " + str(count) + " for " + line)

		
			except BaseException as e:
				import sys

				error_message = "Error: Exception while searching line {}: {} - {}" .format(rowcount, line, e)
				
				sys.stderr.write( error_message )
				error_messages.append(error_message)


	return found, found_near, found_and, found_or, found_similar_and, found_similar_or, rowcount, error_messages

search_list/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />

{% load static from staticfiles %}

	<link rel="stylesheet" href="{% static "css/foundation.css" %}" />
	<script src="{% static "stdlib.js" %}"></script>
	<script src="{% static "js/vendor/modernizr.js" %}"></script>
	<script src="{% static "js/vendor/jquery.js" %}"></script>
	<script src="{% static "js/foundation.min.js" %}"></script>
	<script src="{% static "js/foundation/foundation.topbar.js" %}"></script>
	<script src="{% static "js/foundation/foundation.magellan.js" %}"></script>	

</head>

<body>
<div class="row">
{% block content %}{% endblock content %}
</div>

	<script>
	    $(document).foundation();
	</script>
</body>
</html>

search_list/templates/index.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block content %}


{% if rowcount %}
	<link rel="stylesheet" href="{% static "tablesaw/tablesaw.css" %}">
    <script>
    /* grunticon Stylesheet Loader | https://github.com/filamentgroup/grunticon | (c) 2012 Scott Jehl, Filament Group, Inc. | MIT license. */
    window.grunticon=function(e){if(e&&3===e.length){var t=window,n=!(!t.document.createElementNS||!t.document.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect||!document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#Image","1.1")||window.opera&&-1===navigator.userAgent.indexOf("Chrome")),o=function(o){var r=t.document.createElement("link"),a=t.document.getElementsByTagName("script")[0];r.rel="stylesheet",r.href=e[o&&n?0:o?1:2],a.parentNode.insertBefore(r,a)},r=new t.Image;r.onerror=function(){o(!1)},r.onload=function(){o(1===r.width&&1===r.height)},r.src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw=="}};
	    grunticon(["{% static "tablesaw/icons/icons.data.svg.css" %}", "{% static "tablesaw/icons/icons.data.png.css" %}", "{% static "tablesaw/icons/icons.fallback.css" %}"]);
	</script>
    <noscript><link href="{% static "tablesaw/icons/icons.fallback.css" %}" rel="stylesheet"></noscript>
	<script src="{% static "tablesaw/tablesaw.js" %}"></script>

<a class="button" href="">New search (reset query)</a>

{% if error_messages %}
<h1>Errors</h1>
<ul>
{% for error in error_messages %}
<li>{{ error }}</li>
{% endfor %}
</ul>
{% endif %}


<h1>Search-List results</h1>
<p>Searched for {{ rowcount }} entries with the following search strategies:</p>


<div data-magellan-expedition="fixed">
	<dl class="sub-nav">
	<dd data-magellan-arrival="phrase"><a href="#phrase">Phrase</a></dd>
	<dd data-magellan-arrival="near"><a href="#near">Phrase but words in between</a></dd>
	<dd data-magellan-arrival="and"><a href="#and">All words (AND)</a></dd>
	<dd data-magellan-arrival="similar_and"><a href="#similar_and">All words similar</a></dd>
	<dd data-magellan-arrival="or"><a href="#or">Some words (OR)</a></dd>
	<dd data-magellan-arrival="similar_or"><a href="#similar_or">Some similar words</a></dd>
	</dl>
</div>

<a name="phrase"></a>
<h2 data-magellan-destination="phrase">Phrase found</h2>
<p><i>Exact match of the whole phrase</i></p>
{% if results %}
<p><i>All words found exact in this order and without other words in between</i></p>

<p>Results for {{ found }} entries of {{ rowcount }} searched entries</p>

<table class="tablesaw-swipe" data-mode="swipe" data-sortable data-minimap data-sortable-switch>
<thead>
<th data-sortable-col>Query</th><th data-sortable-col>Results</th>
</thead>
<tbody>
{% for result, values in results.items %}
<tr>
<td>{{ result }}</td>
<td><a target="_blank" href="{{ uri_search }}{{ values.link }}">{{ values.count }}</a></td>
</tr>
{% endfor %}
</tbody>
</table>

{% else %}
<p>No results</p>
{% endif %}



<a name="near"></a>
<h2 data-magellan-destination="near">Phrase found with some words in between</h2>
<p><i>All words found in document in exactly this order but some (max 10) words in between</i></p>

{% if results_near %}

<p>Results for {{ found_near }} entries of {{ rowcount }} searched entries</p>

<table class="tablesaw-swipe" data-mode="swipe" data-sortable data-minimap data-sortable-switch>
<thead>
<th data-sortable-col>Query</th><th data-sortable-col>Results</th><th data-sortable-col>Best score</th>
</thead>
<tbody>
{% for result, values in results_near.items %}
<tr>
<td>{{ result }}</td>
<td><a target="_blank" href="{{ uri_search }}{{ values.link }}">{{ values.count }}</a></td>
<td>{{ values.maxscore }}</td>
</tr>
{% endfor %}
</tbody>
</table>

{% else %}
<p>No results</p>
{% endif %}



<a name="and"></a>
<h2 data-magellan-destination="and">All words found</h2>
<p><i>Maybe matching (all words found in document but not the phrase in exactly this order)</i></p>

{% if results_and %}

<p>Results for {{ found_and }} entries of {{ rowcount }} searched entries</p>

<table class="tablesaw-swipe" data-mode="swipe" data-sortable data-minimap data-sortable-switch>
<thead>
<th data-sortable-col>Query</th><th data-sortable-col>Results</th><th data-sortable-col>Best score</th>
</thead>
<tbody>
{% for result, values in results_and.items %}
<tr>
<td>{{ result }}</td>
<td><a target="_blank" href="{{ uri_search }}{{ values.link }}">{{ values.count }}</a></td>
<td>{{ values.maxscore }}</td>
</tr>
{% endfor %}
</tbody>
</table>

{% else %}
<p>No results</p>
{% endif %}




<a name="similar_and"></a>
<h2 data-magellan-destination="similar_and">Similar words found for all words</h2>
{% if results_similar_and %}
<p><i>Similar words all found in document. Sort for descending score to see the most similar first.</i></p>
<p>Results for {{ found_similar_and }} entries of {{ rowcount }} searched entries</p>

<table class="tablesaw-swipe" data-mode="swipe" data-sortable data-sortable-switch>
<thead>
<th data-sortable-col>Query</th><th data-sortable-col>Results</th><th data-sortable-col>Best score</th>
</thead>
<tbody>
{% for result, values in results_similar_and.items %}
<tr>
<td>{{ result }}</td>
<td><a target="_blank" href="{{ uri_search }}{{ values.link }}">{{ values.count }}</a></td>
<td>{{ values.maxscore }}</td>
</tr>
{% endfor %}
</tbody>
</table>

{% else %}
<p>No results</p>
{% endif %}


<a name="or"></a>
<h2 data-magellan-destination="or">Only some words found</h2>
{% if results_or %}
<p><i>Some words found in document. Sort for descending score to see the most similar first.</i></p>
<p>Results for {{ found_or }} entries of {{ rowcount }} searched entries</p>
<table class="tablesaw-swipe" data-mode="swipe" data-sortable data-sortable-switch>
<thead>
<th data-sortable-col>Query</th><th data-sortable-col>Results</th><th data-sortable-col>Best score</th>
</thead>
<tbody>
{% for result, values in results_or.items %}
<tr>
<td>{{ result }}</td>
<td><a target="_blank" href="{{ uri_search }}{{ values.link }}">{{ values.count }}</a></td>
<td>{{ values.maxscore }}</td>
</tr>
{% endfor %}
</tbody>
</table>

{% else %}
<p>No results</p>
{% endif %}



<a name="similar_or"></a>
<h2 data-magellan-destination="similar_or">Some similar words found</h2>
{% if results_similar_or %}

<p><i>Some words found in document, some of them only similar. Sort for descending score to see the most similar first.</i></p>
<p>Results for {{ found_similar_or }} entries of {{ rowcount }} searched entries</p>

<table class="tablesaw-swipe" data-mode="swipe" data-sortable data-sortable-switch>
<thead>
<th data-sortable-col>Query</th><th data-sortable-col>Results</th><th data-sortable-col>Best score</th>
</thead>
<tbody>
{% for result, values in results_similar_or.items %}
<tr>
<td>{{ result }}</td>
<td><a target="_blank" href="{{ uri_search }}{{ values.link }}">{{ values.count }}</a></td>
<td>{{ values.maxscore }}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% else %}
<p>No results</p>
{% endif %}

<hr/>

{% endif %}



<h1>Search with a list</h1>
<p>Check for each entry if there are search results</p>

<form action="" method="post">{% csrf_token %}



    <div class="fieldWrapper">
        <label for="id_list">List:</label>
        {{ form.list }}
        {{ form.list.errors }}

    </div>


<input class="button" type="submit" value="Search for each list entry" />


<div class="row">


    <div class="small-12 medium-8 columns">


        
        <h3>Fuzzy search</h3>
		<p>Each list entry / line will be searched with following search strategies:</p>
			
		<div>
        {{ form.do_find_phrase }}
        <label for="id_do_find_phrase" title="Used search operators: &quot;open source&quot;">Full phrase exact in this order</label>
        
        </div>
        
		<div>
        {{ form.do_find_near }}
        <label for="id_do_find_near" title="Used search operators: &quot;open source&quot;~10">All words in this order but some words in between</label>
        </div>
        
        
		<div>
        {{ form.do_find_and }}
        <label for="id_do_find_and" title="Used search operators: open AND source">All words in document, but not the searched phrase</label>
        </div>
        
        
		<div>
        {{ form.do_find_or }}
        <label for="id_do_find_or" title="Used search operators: open OR source">Some or most words matching, but not all</label>
        </div>

        
		<div>
        {{ form.do_find_similar_and }}
        <label for="id_do_find_similar_and" title="Used search operators: open~ AND source~">Similar words for all words</label>
        </div>
        
		<div>
        {{ form.do_find_similar_or }}
        <label for="id_do_find_similar_or" title="Used search operators: open~ OR source~">Some or most similar words</label>
        </div>
        
		<p>Searching with fuzzy search will take more time, but will find similar results, too - which often are exactly what you search for but it can not be found by exact matching i.e. because of typos or if a part of a company name like the suffix <i>Ltd.</i> is missing in some documents but is part of your search query. Or you want to find documents even if some chars were recognized wrong while automatic textrecognition (OCR) of scans.</p>

		<p>There will be a result list for each type of the activated searches</p>

		<p>Each additional search type will exclude all results from (better matching but not finding all) activated types/queries before.</p>
		<p>Mouse over to see the used search operators for the list entry example <i>open source</i>.</p>
		
	</div>



    <div class="small-12 medium-4 columns">
    
	
	<h3>Filter query</h3>
		<div>
        {{ form.filterquery.errors }}
        <label for="id_filterquery">Additional filter query:</label>
        {{ form.filterquery }}
<p>Results have to match this additional query part, too. So its not enough to match only the search entry of the list.</p>
<p>I.e. for filtering with additional criterias like a path, person or project name. Or to search only in some documents or data.</p>
    	</div>
    	
    	
    </div>




    <div class="small-12 medium-4 columns">
    
	
	<h3>Ignore words</h3>
		<div>
        {{ form.stopwords.errors }}
        <label for="id_stopwords">Ignore this words in every list entry:</label>
        {{ form.stopwords }}
<p>I.e. name parts like "Ltd." because not so important for matching but not contained in every searched document, which in this case would not match.</p>
    	</div>

    	
    	
    </div>


</div>

</form>

</div>
{% endblock content %}