api/urls.py
from django.conf.urls import url

from api import views

urlpatterns = [
	url(r'^delete', views.queue_delete, name='queue_delete'),
	url(r'^enrich', views.queue_enrich, name='queue_enrich'),
	url(r'^index-web', views.queue_index_web, name='queue_index_web'),
	url(r'^index-rss', views.queue_index_rss, name='queue_index_rss'),
	url(r'^index-file', views.queue_index_file, name='queue_index_file'),
	url(r'^index-filedirectory', views.queue_index_file, name='queue_index_filedirectory'),
	url(r'^index-dir', views.queue_index_file, name='queue_index_dir'),
]

crawler/urls.py
from django.conf.urls import url

from crawler import views

urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^(?P<pk>\d+)/crawl$', views.crawl, name='crawl'),
	url(r'^(?P<pk>\d+)/delete$', views.delete, name='delete'),
	url(r'^recrawl$', views.recrawl, name='recrawl'),
	url(r'^create$', views.create_crawler, name='create'),
	url(r'^(?P<pk>\d+)/update$', views.update_crawler, name='update'),
]

opensemanticsearch/urls.py
from django.conf.urls import include, url

from django.contrib import admin

from django.contrib import auth


urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'^api/', include('api.urls', namespace="api")),
	url(r'^entity_rest_api/', include('entity_rest_api.urls', namespace="entity_rest_api")),
	url(r'^setup/', include('setup.urls', namespace="setup")),
	url(r'^crawler/', include('crawler.urls', namespace="crawler")),
	url(r'^files/', include('files.urls', namespace="files")),
	url(r'^datasources/', include('datasources.urls', namespace="datasources")),
	url(r'^annotate/', include('annotate.urls', namespace="annotate")),
	url(r'^thesaurus/', include('thesaurus.urls', namespace="thesaurus")),
	url(r'^rss_manager/', include('rss_manager.urls', namespace="rss_manager")),
	url(r'^querytagger/', include('querytagger.urls', namespace="querytagger")),
	url(r'^search-list/', include('search_list.urls', namespace="search_list")),
	url(r'^csv/', include('csv_manager.urls', namespace="csv_manager")),
	url(r'^ontologies/', include('ontologies.urls', namespace="ontologies")),
	url(r'^hypothesis/', include('hypothesis.urls', namespace="hypothesis")),
	url(r'^graph/', include('visual_graph_explorer.urls', namespace="graph")),
	url(r'^search_entity/', include('search_entity.urls', namespace="search_entity")),
	url(r'^morphology/', include('morphology.urls', namespace="morphology")),
	url(r'^twitter/', include('twitter.urls', namespace="twitter")),
]

solr_relevance_ranking_analysis/urls.py
from django.conf.urls import url

from solr_relevance_ranking_analysis import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
]

crawler/models.py
from django.db import models


# Types of crawlers
crawler_type_chooices = (
						('PAGE', 'Index only this web page'),
						('PATH', 'Crawl all web pages within this path'),
						('DOMAIN', 'Crawl full domain and subdomains'),
			)


class Crawler(models.Model):

	uri = models.CharField(max_length=1000, blank=False)

	crawler_type = models.CharField(max_length=6,
                                      choices=crawler_type_chooices,
                                      default='PATH')
	
	sitemap = models.CharField(max_length=1000, null=True, blank=True)

	delta = models.IntegerField(default=1440)
	
	title = models.CharField(max_length=1000, blank=True)

	description = models.TextField(blank=True)
	
	last_imported = models.DateTimeField(null=True, blank=True)
	


	def __str__(self):
		
		name = self.title
		
		if not name:
			name = self.uri

		if not name:
			name = self.id
	
		return name

crawler/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import RequestContext
from django.views import generic
from django.forms import ModelForm
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.utils import timezone
from django.shortcuts import redirect


import datetime
from datetime import timedelta

from crawler.models import Crawler


class CrawlerForm(ModelForm):

	class Meta:
		model = Crawler
		fields = '__all__'

class IndexView(generic.ListView):
	model = Crawler

class DetailView(generic.DetailView):
	model = Crawler

class CreateView(generic.CreateView):
	model = Crawler

class UpdateView(generic.UpdateView):
	model = Crawler


#
# New/additional crawler
#

def create_crawler(request):

	if request.method == 'POST':

		form = CrawlerForm(request.POST, request.FILES)

		if form.is_valid():
			crawler = form.save()

			return HttpResponseRedirect( reverse('crawler:detail', args=[crawler.pk]) ) # Redirect after POST

	else:
		form = CrawlerForm()

	return render(request, 'crawler/crawler_form.html', 
			{'form': form,	} )
	

#
# Updated an crawler
#

def update_crawler(request, pk):

	crawler = Crawler.objects.get(pk=pk)
	
	if request.POST:
		
		form = CrawlerForm(request.POST, request.FILES, instance=crawler)
		
		if form.is_valid():
			form.save()

			return HttpResponseRedirect( reverse('crawler:detail', args=[pk])) # Redirect after POST
		
			pass
	else:
		form = CrawlerForm(instance=crawler)

	return render(request, 'crawler/crawler_form.html', 
			{'form': form, 'crawler': crawler } )


def etl(pk):

	last_imported = datetime.datetime.now()

	crawler = Crawler.objects.get(pk=pk)
	
	# add to queue
	if crawler.sitemap:
		# get sitemap and add urls to queue
		from opensemanticetl.tasks import index_sitemap
		index_sitemap.apply_async( kwargs={ 'uri': crawler.sitemap }, queue='open_semantic_etl_tasks', priority=5 )
		
	else:
		if crawler.crawler_type=="DOMAIN" or crawler.crawler_type=="PATH":
			# add website to queue
			from opensemanticetl.tasks import index_web_crawl
			index_web_crawl.apply_async( kwargs={ 'uri': crawler.uri, 'crawler_type': crawler.crawler_type }, queue='open_semantic_etl_tasks', priority=5 )
		else:
			# add web page to queue
			from opensemanticetl.tasks import index_web
			index_web.apply_async( kwargs={ 'uri': crawler.uri }, queue='open_semantic_etl_tasks', priority=5 )

	# save new timestamp
	crawler.last_imported = last_imported
	crawler.save()

#
# Delete entry
#

def delete(request, pk):

	crawler = Crawler.objects.get(pk=pk)
	
	crawler.delete()

	return redirect('crawler:index')


#
# Add website to queue
# So a worker will download/read the website and import/download all new articles
#

def crawl(request, pk):

	etl(pk)

	return render(request, 'crawler/crawler_crawl.html', {'id': pk,})


#
# Add all websites to queue where last import was before configured delta time of the website
#

def recrawl(request):

	verbose = True

	log = []
	count = 0
	count_queued = 0

	for crawler in Crawler.objects.all():

		count += 1

		if verbose:
			log.append( "Checking delta time of website: {}".format(crawler) ) 


		add_to_queue = True

		# If delta 0, no automatic import
		if not crawler.delta:
			add_to_queue = False

		# If delta time, do not import this website within this time by setting add_to_queue to false
		if crawler.delta and crawler.last_imported:

			# when next import allowed (because time delta passed)?
			next_import = crawler.last_imported + timedelta(minutes=crawler.delta)

			# don't check time delta if last import in future (i.e. if system time was wrong)
			if crawler.last_imported < timezone.now():			

				# if time for next import not reached, do not index
				if timezone.now() < next_import:
					add_to_queue = False

			if verbose:
				log.append( "Last addition to queue: {}".format(crawler.last_imported) )
				log.append( "Next addition to queue: {}".format(next_import) ) 


		if add_to_queue:

			if verbose:
				log.append( "Adding website to queue: {}".format(crawler) ) 
			
			etl(crawler.pk)

			count_queued += 1
	
	#
 	# stats / log
 	#
 	
	response = "Websites to queue: {} of {}".format(count_queued, count)

	if len(log) > 0:
		response += "\n\n" + "\n".join(log)
	
	#
	# return response
	#
	
	status = HttpResponse(response)
	status["Content-Type"] = "text/plain" 
	return status

crawler/templates/crawler/crawler_crawl.html
{% extends "datasources_base.html" %}

{% block content %}

<div class="row">
	<div class="small-12 columns">
<p>Website added to queue.</p>
	</div>
</div>

<div class="row">
	<div class="small-12 columns">

<a class="button" href="{% url 'crawler:detail' id %}">Back to dataset details</a>
	</div>
</div>

{% endblock content %}

crawler/templates/crawler/crawler_detail.html
{% extends "datasources_base.html" %}

{% block content %}

<div class="row">
	<div class="small-12 columns">

<a class="button small" href="{% url 'crawler:index' %}">Websites (back to list of all websites)</a>


	</div>
</div>

<div class="row">
	<div class="small-12 columns">

Title or ID:
<h1>{{ crawler.title|default:crawler.id }}</h1>

	{% if crawler.uri %}
	<p>
	URI: {{ crawler.uri }}
	</p>
	{% endif %}

	{% if crawler.sitemap %}
	<p>
	Sitemap: {{ crawler.sitemap }}
	</p>
	{% endif %}


	{% if crawler.description %}

	{{ crawler.description }}

	{% endif %}

	</div>
</div>


<div class="row">
	<div class="small-12 columns">

<h3>Actions</h3>

<a class="button" href="{% url 'crawler:crawl' crawler.id %}">Index website</a></li>

<a class="button" href="{% url 'crawler:update' crawler.id %}">Edit settings</a>


	</div>
</div>

{% endblock content %}

crawler/templates/crawler/crawler_form.html
{% extends "datasources_base.html" %}

{% block content %}

<form {% if form.is_multipart %}enctype="multipart/form-data"{% endif %} action="" method="post">{% csrf_token %}

    {{ form.non_field_errors }}

<div class="row">

	<div class="small-12 columns">


{% if crawler.id %}
<h1>Edit crawler</h1>
{% else %}
<h1>Add crawler for website</h1>
{% endif %}



	</div>
</div>




<div class="row">

	<div class="small-12 columns">


<dl class="tabs" data-tab>
  <dd><a href="#panel-title">Description (optional)</a></dd>
  <dd class="active"><a href="#panel-datasource">URL and frequency</a></dd>
  <dd><a href="#panel-sitemap">Sitemap (optional)</a></dd>
</dl>

	</div>
</div>










<div class="tabs-content">

  <section class="content" id="panel-title">


<div class="row">
	<div class="small-12 columns text-center">
<h2>Name or notes</h2>
	</div>
</div>

<div class="row">
	<div class="small-12 columns">


<p>Not necessary, only for managing purpose</p>

        {{ form.title.errors }}
        <label for="id_title">Title:</label>
        {{ form.title }}

<div class="row">

    <div class="small-12 medium-8 columns">
    <h3>Notes</h3>
        {{ form.description.errors }}
        <label for="id_description">Description or Notes</label>
        {{ form.description }}
    </div>


</div>

</section>

  <section class="content active" id="panel-datasource">

<div class="row">

	<div class="small-12 columns text-center">

<h2>URL (Address)</h2>

        {{ form.uri.errors }}
        <label for="id_uri">URI:</label>
        {{ form.uri }}
	<p>For example <i>http://www.opensemanticsearch.org/</i></p>


        {{ form.crawler_type.errors }}
        <label for="id_crawler_type">How much to crawl?</label>
        {{ form.crawler_type }}
	<p>Be carefull, crawling whole domains can lead to much load and blockings or even not possible if too many pages/data.</p>


<h2>Frequency (Delta time)</h2>



        {{ form.delta.errors }}
        <label for="id_delta">Delta time (minutes):</label>
        {{ form.delta }}
	<p><i>For example 60 for indexing every hour or 1440 for indexing daily</i></p>


    </div>


</div>




</section>



  <section class="content" id="panel-sitemap">


<div class="row">
	<div class="small-12 columns text-center">
<h2>Sitemap</h2>
	</div>
</div>

<div class="row">
	<div class="small-12 columns">

<p>Index all web pages configured in sitemap.xml instead of the given URL/Homepage</p>

        {{ form.sitemap.errors }}
        <label for="id_sitemap">URL of sitemap.xml:</label>
        {{ form.sitemap }}

	</div>

</section>



<hr>


<div class="row">
    <div class="small-12 columns">

<h2>Save changes</h2>

    <input class="button" type="submit" value="Save" />



{% if crawler.id %}
    <a class="button" href="{% url 'crawler:detail' crawler.id %}">Cancel</a>
{% else %}
    <a class="button" href="{% url 'crawler:index' %}">Cancel</a>
{% endif %}

</div>
</div>

</form>
{% endblock content %}

crawler/templates/crawler/crawler_list.html
{% extends "datasources_base.html" %}

{% block content %}


<div class="row">
	<div class="small-12 columns">

<br>
	
<ul class="breadcrumbs"><li><a href="{% url 'datasources:index' %}">Datasources</a></li>

 <li class="current"><a href="#">Websites</a></li> 
  </ul>

<h1>Websites</h1>
<p>Websites for indexing</p>

<a class="button" href="{% url 'crawler:recrawl' %}">Check websites</a>

<a class="button" href="{% url 'crawler:create' %}">Add new Website</a>


	</div>
</div>


<div class="row">
	<div class="small-12 columns">
<h2>All websites</h2>



{% if crawler_list %}
    <ul>
    {% for crawler in crawler_list %}
        <li><h2><a href="{% url 'crawler:detail' crawler.id %}">{{ crawler.title|default:crawler }}</a></h2>
            <a class="button small" href="{% url 'crawler:crawl' crawler.id %}">Index now</a>
            <a class="button small" href="{% url 'crawler:detail' crawler.id %}">Details</a>
            <a class="button small" href="{% url 'crawler:update' crawler.id %}">Edit settings</a>
            <a class="button small" href="{% url 'crawler:delete' crawler.id %}" onclick="return confirm('Are you sure you want to delete this entry?')">Delete</a>

        </li>
    
    {% endfor %}
    </ul>
{% else %}
    <p>No crawlers yet.</p>
{% endif %}


	</div>
</div>


{% endblock content %}

crawler/templates/crawler/crawler_recrawl.html
{% extends "datasources_base.html" %}

{% block content %}

<div class="row">
	<div class="small-12 columns">
<p>Websites added to queue.</p>
	</div>
</div>

<div class="row">
	<div class="small-12 columns">

<a class="button" href="{% url 'crawler:index' %}">Back</a>
	</div>
</div>

{% endblock content %}